modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="dimensions"
version="1.0.0"
displayName="Dimensions+"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Hugo, MCreator"

[[dependencies.dimensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



